AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: nWAY API
        
Resources:

  # do not delete this mark
  # deploy will use it to inject cloudformation resources.

  # @INJECT